Esri/feedback-js-api-next

- README.md
This repository is awesome!
Many people use `esri-loader` to fetch the API, so quickly added two lines on using the next release in that environment.
> Added guidance for esri-loader

- CHANGELOG.md
This update adds a breaking change notice for the removal of the default setting for `config.assetsPath`.
> Add breaking change to CHANGELOG

- CHANGELOG.md
Critical dependency warnings fixed in `4.19.0-next.20210216`.
> CHANGELOG fixed critical dependency warnings in ESM builds

- CHANGELOG.md
This is just a small update to doc the upcoming change to how ESM assets are handled. Users can still override the default with `config.assetsPath` when working with a local copy of the assets.
cc @annelfitz
> Update CHANGELOG with info on ESM assets defaulting to CDN

- ES_modules.md
HOLD merging until 4.19 release. 
cc @dasa
> Remove ES modules beta overview page.

- CHANGELOG.md
Async/await support at runtime for the APIs AMD modules will be required. For example, this may affect Angular apps using esri-loader.
@dasa this is pretty much a mirror copy of the release notes.
> Update deprecations list

- CHANGELOG.md
**Cannot be merged until `/next` CDN builds on monday.**
- Adds WMSLayer popup change to CHANGELOG. Codepen linked will be broken until `/next` is updated.
- Adds BasemapToggle toggle event breaking change
> Add WMSLayer enhancement & basemaptoggle breaking change

- .github/workflows/stale.yml
This PR upgrades `actions/stale` from `v4` to `v7`.
> Update stale github action

- .github/ISSUE_TEMPLATE/a-issue-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement-report.yml
Updates include:
- Moves the standard issue template to the top of the list
- Clarified and tightened up wording in the Enhancement template
- Updated several links that were pointing to the wrong repo
- Added a link to ArcGIS Ideas
> Updates to issue templates

- CHANGELOG.md
Adds a section for calcite icon support in the Expand widget, and a CIMSymbol bug fix from Esri Community
> Add Expand calcite icon support and a CIMSymbol bug fix

- CHANGELOG.md
This PR adds information regarding the view popup changes that may cause apps to break. It details out what people need to do to migrate if they have breaking changes. Once the functionality is installed (currently targeted for Tuesday 4/11), I will add some codepen examples to showcase the changes and this PR can be merged so customers can test the functionality.
@ycabon @bsvensson @annelfitz could you please review the content and once this is approved, I can add some examples and merge next week? Thanks!
> Add view popup migration and breaking changes to the changelog

- CHANGELOG.md
Adds a bug fix for TextSymbol.backgroundColor from Esri Community
@lboyd93 can you review?
> Add TextSymbol Esri Community bug fix

- CHANGELOG.md
These deprecated TypeScript definitions will be removed at 4.28.
> Update TS deprecation notice for IPromise and *Constructor

- CHANGELOG.md
Change notice for future Webpack compatibility. There have been quite a few improvements in Webpack recently and they have gone to weekly releases.
> doc(changelog): webpack versions deprecation notice

- CHANGELOG.md
These changes improve understanding the types when they need to be re-exported, for example when working with stencil.js.
> docs(changelog): IPromise and *Constructor removed from typings

- CHANGELOG.md
- Adds the new `LayerList.style` and `BasemapLayerList.style` properties to the changelog
- Deprecates the "classic" possible value for `LayerList.style` and `BasemapLayerList.style`
@annelfitz can you please review.
> docs(changelog): add LayerList style property

- CHANGELOG.md
this should wait to merge until the next build of the `/next` CDN (when the change is picked up)
> Add SVG SimpleMarkerSymbol bug fix

- CHANGELOG.md
Add breaking change note - @types/arcgis-js-api is being deprecated on NPM at 4.28.
> docs(changelog): breaking change for @types/arcgis-js-api

- CHANGELOG.md
`esri-loader` will be deprecated at 4.29. 
@odoe can you take a quick look?
> docs(changelog): esri-loader deprecation notice

- README.md
Various updates:
- Clarify using npm CSS with `@next`
- Add [Deprecation notice](https://github.com/Esri/feedback-js-api-next/pull/275) to the esri-loader section
- Minor syntax tweaks
> docs(README): doc npm css usage with @next 

- CHANGELOG.md
- README.md
This PR updates the CHANGELOG and README.
> docs(changelog): deprecation notice for the AMD npm package `arcgis-js-api`

- README.md
Sync the README and CHANGELOG version shields.  We switched to using @arcgis/core. I missed this on my previous PR.
> chore: sync version shields

- CHANGELOG.md
This PR adds a Legend update for supporting definition expressions
> docs(changelog): legend definition query support

- CHANGELOG.md
Clarify that the last release of the `arcgis-js-api` (AMD) package on npm is 4.31. This does not affect the AMD CDN, components or @arcgis/core.
> docs(changelog): update AMD npm breaking change wording

- CHANGELOG.md
adds note to changelog about calcite 3.0, warning users there may be instabilities over the next few days.
also adds current breaking changes for 4.32
> update changelog with note about calcite 3.0
