README.md
Add a section on how to the the `@next` TypeScript typings.
=> add typescript typings instructions

README.md
Adding a bit of context on how to use the /next css.
cc @bsvensson @jcfranco @tomwayson
=> Add css usage info to README

README.md
=> Update esri-loader css url

.github/ISSUE_TEMPLATE/bug_report.md
Added text for user to verify if an Esri Tech Support issue has been opened.
=> Update to bug_report issue template

ES_modules.md
Update the supported browsers info.
=> Update supported browsers FAQ

esm-samples/jsapi-angular-cli/README.md, esm-samples/jsapi-angular-cli/src/app/app.component.ts, esm-samples/jsapi-create-react-app/package.json, esm-samples/jsapi-ember-cli/package.json, esm-samples/jsapi-node/package-lock.json, esm-samples/jsapi-node/package.json, esm-samples/jsapi-node/src/projection.js, esm-samples/jsapi-vue-cli/package.json, esm-samples/rollup/package.json, esm-samples/webpack/package.json
This PR updates the samples for use with the latest `@arcgis/core` next release.
=> update for latest next release

CHANGELOG.md
This was a suggestion from @steveoh. Thanks @steveoh!
=> Add clarifications on config.assetsPath in CHANGELOG

CHANGELOG.md, README.md
=> Initial update for 4.21

.github/workflows/stale.yml
@bsvensson for your review.
Items that were updated:
* Changed cron job to midnight UTC.
* Removed PR checks and notifications
* Set days to stale at 365
* Updated the stale issue message to include a blurb about tech support.
=> Auto close stale issues.

CHANGELOG.md, README.md
=> Initial commit for 4.22

CHANGELOG.md, README.md
=> Update to 4.23

CHANGELOG.md, README.md
Updates to changelog and readme for 4.24!
=> Update for 4.24

CHANGELOG.md
Updates to changelog for tasks removal breaking change for 4.24.
=> Update changelog for tasks removal

CHANGELOG.md, README.md
This PR updates the change log and read me to reflect the new release date for 4.25 (November 2022).
=> Update 4.25 release date

CHANGELOG.md
Add notes about `IPromise` and `*Constructor`
cc @bsvensson @odoe
=> Add deprecated typings info.

CHANGELOG.md
ready for merge after the next `/next` CDN release goes out, most likely on Monday 10/3
=> Add bug fix for BUG-000152279

CHANGELOG.md
Add `RelationshipContent` to changelog with a codepen example.
=> Update CHANGELOG.md with RelationshipContent Info

CHANGELOG.md
Adding ENH-000116507 information to CHANGELOG. Ready for merge!
=> Add ENH-000116507 to CHANGELOG.md

CHANGELOG.md
Add bug fix to the changelog for missing field alias in Legend.
@lboyd93 can you please review?
=> Changelog - Add bug fix for missing field alias in Legend

CHANGELOG.md
Add a description for ControlPointGeoreference under layers
=> Changelog - add ControlPointGeoreference

CHANGELOG.md
Add two updates for MapImageLayer to changelog.
=> update changelog with MapImageLayer updates

CHANGELOG.md
@bsvensson can you please review?  Just adding a couple code snippets to the ControlPointsGeoreference section.
=> Add descriptions of ControlPointGeoreference methods

CHANGELOG.md
This PR would add descriptions of LayerList and BasemapLayerList indicator changes to the changelog
@bsvensson can you please review?
=> add LayerList and BasemapLayerList changes to changelog

CHANGELOG.md, README.md
This PR updates the changelog and readme for 4.26.
@annelfitz will you review please? Thanks!
=> Update for 4.26

CHANGELOG.md
Update the bug and enhancements list on the change log.
=> Update bugs and enhancements

CHANGELOG.md
Add new bug fix to the CHANGELOG
=> Add popup chart bug fix to CHANGELOG

.github/ISSUE_TEMPLATE/enhancement-report.yml
I wanted to submit a new enhancement, but the `Enhancement` category was missing from the `New Issue` panel, so I decided to lurk around the `.github` repository folder, because in the past I had already submitted some enhancements using a template. While doing that, I discovered an indentation problem within the existing `Enhancement` template.
So I created this PR, to fix the indentation problem.
=> Fix indentation in Enhancement issue template

CHANGELOG.md
This PR adds the new popup features to the changelog.
@bsvensson - could you please review?
=> Add Popup Updates to CHANGELOG

CHANGELOG.md
=> StreamLayer updates

CHANGELOG.md
- add blurb about adding media layer persistence in web maps.
=> add media layer persistence in web maps

CHANGELOG.md
@annelfitz can you please review?
=> add changes to legend widget

CHANGELOG.md, README.md
=> Update repo to 4.27

CHANGELOG.md
Adding latest bug fixes/enhancements for 4.27 to the changelog
=> Update bug fixes/enhancements in CHANGELOG for 4.27

CHANGELOG.md
=> chore(changelog) - breaking change reverting to native support for async/await at runtime (AMD)

CHANGELOG.md
Could you please review @annelfitz ? Thanks!
=> Add ImageMediaInfo fix to changelog

CHANGELOG.md
Adds ScaleBar updates to the changelog. @bsvensson / @lboyd93 can you review?
=> Add ScaleBar updates

CHANGELOG.md
Adds doc for the new `view.ui.getComponents()` method. @lboyd93 can you review?
=> docs: add view.ui.getComponents to changelog

CHANGELOG.md
This PR adds the fix for MapImageLayer popups not working hen the features did not have a renderer.
=> doc(change log): Add MIL popup fix

CHANGELOG.md
Adds an alt text accessibility issue and info about MediaLayer being taken out of beta to the changelog.
=> doc(changelog): add bug fixes and enhancements

CHANGELOG.md
This adds notes about Track widget and updates to the local asset version mismatch warning.
=> doc(changelog): track widget and local asset updates

CHANGELOG.md
Added Popup design update information to the change log. Could you please review, @annelfitz ?
=> doc(change log): popup design updates

CHANGELOG.md
- fixed link for MediaLayer
- added enhancement about async `filterFunction` support
=> Add async filterFunction on PortalBasemapsSource

CHANGELOG.md
- Add new bug fix for CIMSymbols with primitive overrides published from Pro
- Reorders bugs/enhancements so they are more alphabetical
- Adds breaking change
@lboyd93 can you review?
=> add CIM Pro prim override fix, update bug fix/enhancement order

CHANGELOG.md
- Updates the CHANGELOG.md with a description of the new animated image support with MediaLayer
- Looks like some formatting changes snuck their way in too.
=> docs(changelog): MediaLayer ImageElement animationOptions

CHANGELOG.md
- Updates the `ImageElement.animationOptions` public properties and changes the casing on the allowed values for `repeatType` to be lowercase
=> docs(changelog): update ImageElement.animationOptions

CHANGELOG.md
This PR adds the update for Popups so that they are always expanded no matter the size of the View.
=> docs(change log): Add popup expand enhancement

CHANGELOG.md
Adds section about the Basemap styles service (v2)
=> Add Basemap styles service (v2)

CHANGELOG.md
This PR updates the changelog to
- Rename the LayerList and BasemapLayerList `default` style value to `modern`
- Add an enhancement for improving the styles of empty group layers
=> docs(changelog): LayerList and BasemapLayerList updates

CHANGELOG.md
This PR adds info on the `colors` property and the popup design updates for this release.
=> docs(change log): Add popup colors and design updates

CHANGELOG.md
This PR updates and re-orders the bug list and adds the missing breaking changes.
=> docs(change log): Update bug list and breaking changes

CHANGELOG.md
- This PR removes the section about LayerList and BasemapLayerList styles and the deprecation notices for those properties.
=> docs(changelog): remove styles

CHANGELOG.md
- renames the `playAnimation` property `playing`
- merge after next is published again
=> docs(changelog): rename playAnimation property playing

CHANGELOG.md, README.md
@annelfitz can you take a look? 
/cc @bsvensson
=> chore: update to 4.29

CHANGELOG.md
@annelfitz could you please review? Thanks!
=> docs(change log):Add Popup VisibleElements changes & remove old bugs/enh from list

CHANGELOG.md
@lboyd93 can you review when you get a minute?
=> docs(changelog): add WebGL 2 notice

CHANGELOG.md
@annelfitz  could you please review? Thanks!
=> docs(change log): Add IWA trustedServers change

CHANGELOG.md
- adds an topic and a breaking change to the changelog for the LayerList calcite refactor
=> docs(changelog): add layer list changes

CHANGELOG.md
Adds Popup/Features display order update, breaking changes for Popup, and a couple of bugs/enh to the list.
=> docs(change log): Add Popup display order updates & bugs/enh list

CHANGELOG.md
Updates the changelog with several new properties and deprecations for the layer list widgets dealing with selection and reordering of list items.
@annelfitz or @bsvensson can you please review?
=> docs(changelog): layer list updates

CHANGELOG.md
Adds section on pagination of WFSLayers. @lboyd93 can you review?
=> Add WFS pagination

CHANGELOG.md
Adds info about the new `mode` prop on ScaleRangeSlider
=> ScaleRangeSlider.mode

CHANGELOG.md
This should probably wait to be merged until the next update (Monday?).
@annelfitz could you review please? Thanks!
=> docs(change log): Add hitTest improvements & update bug/enh list

CHANGELOG.md
Add note about map components coming out of beta.
=> docs(changelog): add Components updates section

CHANGELOG.md
Adds a note about Expand now using calcite components
=> Add Expand widget update

CHANGELOG.md
Add note about changes to default navigational components in the view.
=> docs(changelog): breaking changes to default nav components

CHANGELOG.md
Breaking change for non-view based events in components.
=> docs(changelog): component event name changes

README.md
Update to README:
* Adjust wording to accommodate components
* Add new component sections for CDN and npm
* Clarifies retirement version for esri-loader
=> chore(README): add components info

CHANGELOG.md
This PR adds LayerList KnowledgeGraphLayer support to the changelog.
@annelfitz can you please review?
=> docs(changelog): layer list knowledge graph layer support

CHANGELOG.md
- Adds three bug fixes to the changelog
=> Update bug fixes

CHANGELOG.md
- Add VideoLayer and CatalogLayerList to the changelog
- Adds LayerList and Legend bug fixes
=> docs(changelog): add VideoLayer, CatalogLayerList and bug fixes

CHANGELOG.md
Adds BUG-000166013 and BUG-000169299
=> Add bug fixes

CHANGELOG.md
copies over latest breaking changes, bug fixes, and enhancements
=> Update breaking changes & bug fixes/enhancements

CHANGELOG.md
This PR adds the updates to MapImageLayer sublayer popup order and adds the fixed bugs/enh to the list.
=> docs(change log): Add MIL updates & update bug/enh list

CHANGELOG.md
=> docs(change log): typings updates

CHANGELOG.md
Adds bug fixes/enhancements so far for 4.33
=> Add 4.33 bug fixes to changelog

CHANGELOG.md
This PR adds VideoPlayer to the deprecation list.
=> docs(changelog): deprecate VideoPlayer

CHANGELOG.md
This PR updates the fixed bug and enh list and adds the Popup/Features enhancement.
=> docs(changelog): Add popup enhancements & bug list

CHANGELOG.md
Adds section for the shadow dom and slots updates for map components.
=> Map components - shadow dom and slots update
